export const CHECKLIST = [
    "Worked from SFO",
    "Worked from YYZ",
    "Worked from VIE",
    "Worked from SEA",
    "Worked from AMS",
    "Asked about the New York office and found out it doesn't exist",
    "Exercised options",
    "Participated in a tender offer",
    "Gotten a raise",
    "Gotten a promotion",
    "Gotten in trouble with Legal",
    "Been a Sentry intern",
    "Returned to Sentry after completing an internship",
    "Celebrated your one year Sentriversary",
    "Celebrated your five year Sentriversary",
    "Celebrated your ten year Sentriversary",
    "Gone on sabbatical",
    "Merged a PR to sentry",
    "Merged a PR to getsentry",
    "Merged a PR to sentry-options-automator",
    "Told a friend that you worked at Sentry and they knew what it was",
    "Told a friend that you worked at Sentry and they didn't know what it was",
    "Gotten a friend to join Sentry",
    "Received feedback from a friend who uses Sentry",
    "Sold a customer on Sentry",
    "Been @-ed by a customer on a GitHub issue",
    "Sudoed into a customer account for a flimsy reason",
    "Accidentally modified customer data",
    "Taken a customer call at an ungodly hour",
    "Messed up a rebase and tagged the whole company on a PR",
    "Bent down awkwardly to check if a meeting room was occupied",
    "Been on a walking one on one in Salesforce Park",
    "Played Killer Queen",
    "Forgotten your badge",
    "Been stuck in the SFO stairwell",
    "Been stuck in the YYZ elevator",
    "Owned at least one article of Sentry-branded clothing",
    "Owned at least five articles of Sentry-branded clothing",
    "Worn an outfit of entirely Sentry-branded clothing",
    "Went on a karaoke outing",
    "Stayed at a happy hour after midnight",
    "Played Dutch Blitz",
    "Been featured in Das Office",
    "Crawled through the Spider Box",
    "Fallen asleep in the library",
    "Participated in Hackweek",
    "Worked on a Hackweek project that no one uses anymore",
    "Worked on a Hackweek project that made it to production",
    "Created a slide deck",
    "Recorded a Show and Tell presentation",
    "Been name dropped in an All Hands meeting",
    "Presented at an All Hands meeting",
    "Received a Sentry Snaps gift card",
    "Won a Value Award",
    "Won a Hackweek award",
    "Written a shipped post",
    "Written a public-facing blog post",
    "Been featured on Sentry social media",
    "Had a slackmoji of yourself",
    "Had a slackbot response for yourself",
    "Uploaded a slackmoji",
    "Created a slackbot response",
    "Yubikeyed in a company-wide channel",
    "Joined #z-aguacooler",
    "Dented in #z-aguacooler",
    "Gibbed a 🥔",
    "Received a 🥔",
    "Accidentally gibbed someone a 🥔 because they were tagged in a message",
    "Been on the weekly 'top taters' Slack report",
    "Broke prod",
    "Caused an incident",
    "Caused a P0 incident",
    "Been paged for an incident at an ungodly hour",
    "Been 🧀-ed on Slack",
    "Hit the reaction limit on Slack",
    "Attended a holiday party",
    "Gotten sloshed at a holiday party",
    "Worked a conference booth",
    "Given a talk at a conference",
    "Gone to R&G Lounge for a goodbye dinner",
    "Lurked the new grad channel and felt old",
    "Had an office crush",
    "Had an office relationship",
    "Gotten spicy in the office",
    "Had an office enemy",
    "Cried because of a coworker",
    "Made a coworker cry",
    "Taken a \"sick day\"",
    "Not RTO-ed on an RTO day",
    "Come into the office on a weekend",
    "Come into the office while technically OOO",
    "Left your trash in a meeting room",
    "Left your dishes in the bathroom",
    "Used the office as your personal grocery store",
    "Gotten into a slack thread argument with over 100 messages",
    "Gotten into a fight with David Cramer on Slack",
    "Gone through the Sentry IPO",
    "Retired with money from the Sentry IPO",
    "Willingly left Sentry",
    "Been fired from Sentry"
]